modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="choups_cyber_dogs"
version="1.0.0"
displayName="Choup's Cyber Dogs"
displayURL="https://github.com/Choupiclou/Choup-s-Cyber-Dog-Mod"
logoFile="logo.png"
credits="Created by choup !"
authors="choup, MCreator"
description="Add cool cyber dogs to MC!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.choups_cyber_dogs]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.choups_cyber_dogs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.choups_cyber_dogs]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.choups_cyber_dogs]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.choups_cyber_dogs]]
    modId="playeranimator"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.choups_cyber_dogs]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config="mixins.choups_cyber_dogs.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration